# Generated by Django 2.2.4 on 2019-08-24 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('ref', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('ref', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=4)),
                ('date', models.DateField(auto_now=True)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('operation', models.CharField(choices=[('b', 'buy'), ('s', 'sell')], max_length=1)),
                ('closed', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_portfolio', to='portfolios.Portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('ref', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=4)),
                ('date', models.DateField(auto_now=True)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('expiration', models.DateField()),
                ('operation', models.CharField(choices=[('c', 'call'), ('p', 'put')], max_length=1)),
                ('closed', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_portofolio', to='portfolios.Portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
