# Generated by Django 2.2.4 on 2019-08-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190825_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'get_latest_by': 'created', 'ordering': ['-user', '-symbol'], 'verbose_name': 'favorite', 'verbose_name_plural': 'favorites'},
        ),
    ]
