# Generated by Django 2.2.4 on 2019-08-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20190825_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-user', '-symbol'], 'verbose_name': 'favorite', 'verbose_name_plural': 'favorites'},
        ),
    ]
