# Generated by Django 2.2.4 on 2019-08-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_plannedsharesoperations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedsharesoperations',
            options={'ordering': ['-user', '-symbol', '-schedule_start', '-date', '-timestamp'], 'verbose_name': 'planned_shares_operation', 'verbose_name_plural': 'planned_shares_operations'},
        ),
        migrations.RenameField(
            model_name='plannedsharesoperations',
            old_name='time',
            new_name='schedule_start',
        ),
        migrations.RemoveField(
            model_name='plannedsharesoperations',
            name='day',
        ),
    ]
