# Generated by Django 2.2.4 on 2019-08-25 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0007_auto_20190825_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlannedSharesOperations',
            new_name='ScheduledSharesOperations',
        ),
        migrations.AlterModelOptions(
            name='scheduledsharesoperations',
            options={'ordering': ['-user', '-symbol', '-schedule_start', '-date', '-timestamp'], 'verbose_name': 'scheduled_shares_operation', 'verbose_name_plural': 'scheduled_shares_operations'},
        ),
    ]
