# Generated by Django 2.2.4 on 2019-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20190825_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledsharesoperations',
            options={'ordering': ['-user', 'schedule_start', '-symbol', '-date', '-timestamp'], 'verbose_name': 'scheduled_shares_operation', 'verbose_name_plural': 'scheduled_shares_operations'},
        ),
        migrations.AlterField(
            model_name='scheduledsharesoperations',
            name='operation',
            field=models.CharField(choices=[('b', 'buy'), ('s', 'sell'), ('c', 'close')], max_length=1),
        ),
    ]
