# Generated by Django 2.2.4 on 2019-08-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20190827_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsharesoperations',
            name='share_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Share'),
        ),
    ]
