# Generated by Django 2.2.4 on 2019-08-24 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('ident', models.UUIDField(default=uuid.UUID('f66e7668-b650-4a49-91f5-0c26e801f396'), editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0.0, max_length=16)),
            ],
        ),
    ]
