# Generated by Django 2.2.4 on 2019-08-24 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('6f688837-da79-438e-943a-6c53e9966507'), editable=False, primary_key=True, serialize=False),
        ),
    ]
