# Generated by Django 2.2.4 on 2019-08-24 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20190824_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('1998b7d8-c8f1-4e84-a78b-22845c66b734'), editable=False, primary_key=True, serialize=False),
        ),
    ]
