# Generated by Django 2.2.4 on 2019-08-25 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20190824_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('e05bba9e-7f8a-4dab-8d21-189ef4ab079e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
