# Generated by Django 2.2.4 on 2019-08-25 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20190825_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('b7deb51b-24d1-47a8-8fbc-1587d7336061'), editable=False, primary_key=True, serialize=False),
        ),
    ]
