# Generated by Django 2.2.4 on 2019-08-25 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_auto_20190825_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('79d634fc-b895-4404-a1c4-c5a3df4f2285'), editable=False, primary_key=True, serialize=False),
        ),
    ]
