# Generated by Django 2.2.4 on 2019-08-25 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_auto_20190825_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('a3c7865a-f7af-4c75-815e-ef368bca0ef8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
