# Generated by Django 2.2.4 on 2019-08-25 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_auto_20190825_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('18a647d7-9c24-4dc5-93fc-a3eea67b25c9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
