# Generated by Django 2.2.4 on 2019-08-25 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_auto_20190825_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('8573f885-46e1-4902-bf9c-f7a648648e96'), editable=False, primary_key=True, serialize=False),
        ),
    ]
