# Generated by Django 2.2.4 on 2019-08-26 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_auto_20190825_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('80134ba0-8494-42b8-a16a-f9771489826c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
