# Generated by Django 2.2.4 on 2019-08-26 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_auto_20190826_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('399c3adf-4349-4ea6-95ea-ba1d6e874f73'), editable=False, primary_key=True, serialize=False),
        ),
    ]
