# Generated by Django 2.2.4 on 2019-08-26 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_auto_20190826_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('faf2c99a-3a76-4d3d-9d32-d96aa2aeef32'), editable=False, primary_key=True, serialize=False),
        ),
    ]
