# Generated by Django 2.2.4 on 2019-08-26 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0015_auto_20190826_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('0412d112-6add-43de-ae81-fb50db741c27'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
