# Generated by Django 2.2.4 on 2019-08-26 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0016_auto_20190826_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('1c2237b0-8438-4d55-b494-c231bc905804'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
