# Generated by Django 2.2.4 on 2019-08-24 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20190824_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('1a60ac6d-1182-4459-8907-7d7df09a609d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
