# Generated by Django 2.2.4 on 2019-08-24 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_auto_20190824_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('7ec60392-89cc-4020-838e-e4817ffb994e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
