# Generated by Django 2.2.4 on 2019-08-24 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_auto_20190824_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('843e9041-0068-4da4-bc55-2a51643b29cf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
