# Generated by Django 2.2.4 on 2019-08-24 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_auto_20190824_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('8e02ad61-3437-4847-8887-71d7c0833cc1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
