# Generated by Django 2.2.4 on 2019-08-24 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_auto_20190824_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('46545322-38e7-4186-bfe1-2418ac460e92'), editable=False, primary_key=True, serialize=False),
        ),
    ]
