# Generated by Django 2.2.4 on 2019-08-24 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_auto_20190824_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('8ba93fa7-f938-477a-8caf-910592dccda8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
