# Generated by Django 2.2.4 on 2019-08-24 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_auto_20190824_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('a8aec5ab-fef6-4e8a-9f0b-f4b8be47d1a9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
