# Generated by Django 2.2.4 on 2019-08-25 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_auto_20190824_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('5b24808a-97c2-43ed-b43a-f40c8e56c21b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
