# Generated by Django 2.2.4 on 2019-08-25 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_auto_20190825_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('8394230b-addc-41e9-8402-e96be2aeedbd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
