# Generated by Django 2.2.4 on 2019-08-25 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0013_auto_20190825_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('a15ab476-057d-4ed8-bdec-623e5e86978a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
