# Generated by Django 2.2.4 on 2019-08-25 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0014_auto_20190825_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('38b40d9b-f7aa-4bdd-91fe-135fdfcfd05b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
