# Generated by Django 2.2.4 on 2019-08-25 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0015_auto_20190825_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('cc2e3a9b-06c6-4f1b-9c6c-9bb3abb8b3c4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
