# Generated by Django 2.2.4 on 2019-08-25 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0016_auto_20190825_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('6f47f76c-13d3-4d6c-8005-ea54f4083aab'), editable=False, primary_key=True, serialize=False),
        ),
    ]
