# Generated by Django 2.2.4 on 2019-08-26 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0018_auto_20190826_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('6610e4cc-d368-4c2e-93de-4c22fa56d678'), editable=False, primary_key=True, serialize=False),
        ),
    ]
