# Generated by Django 2.2.4 on 2019-08-26 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0019_auto_20190826_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('a5e7fb6c-9abf-42e4-a8d7-2b7bf3913bda'), editable=False, primary_key=True, serialize=False),
        ),
    ]
