# Generated by Django 2.2.4 on 2019-08-26 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0020_auto_20190826_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('81ffd261-09f1-4fbe-8aee-798689867563'), editable=False, primary_key=True, serialize=False),
        ),
    ]
