# Generated by Django 2.2.4 on 2019-08-26 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0021_auto_20190826_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('df1502ec-9f17-455c-9254-3a727a845665'), editable=False, primary_key=True, serialize=False),
        ),
    ]
