# Generated by Django 2.2.4 on 2019-08-26 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0022_auto_20190826_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('673e2c6c-d874-4872-8cde-1b5285330f45'), editable=False, primary_key=True, serialize=False),
        ),
    ]
