# Generated by Django 2.2.4 on 2019-08-26 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0025_auto_20190826_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('15bb8d87-d30c-43a0-a97f-dfba4d347a24'), editable=False, primary_key=True, serialize=False),
        ),
    ]
