# Generated by Django 2.2.4 on 2019-08-26 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0026_auto_20190826_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('b70fd118-c18c-4417-9417-78c2d96eef9d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
