# Generated by Django 2.2.4 on 2019-08-26 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0027_auto_20190826_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ident',
            field=models.UUIDField(default=uuid.UUID('ab73e478-22c4-4999-89da-01a296dd73ec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
